const flashcardsData = [
    {"titulo":"Estadística Descriptiva","descripcion":"Resume y organiza datos para entenderlos.","detalles":["Tablas, histogramas, gráficos de barras, boxplots.","Medidas de tendencia central: media, mediana, moda.","Medidas de dispersión: rango, varianza, desviación estándar, percentiles.","Medidas de forma: asimetría, curtosis."]},
    {"titulo":"Estadística Inferencial","descripcion":"Permite generalizar de una muestra a una población.","detalles":["Estimación de parámetros (puntual y por intervalos de confianza).","Pruebas de hipótesis (Z, t, chi-cuadrado, ANOVA).","Consideraciones sobre error y significancia estadística."]},
    {"titulo":"Probabilidad","descripcion":"Modela la incertidumbre y eventos aleatorios.","detalles":["Probabilidad clásica, condicional, conjunta.","Teorema de Bayes.","Variables aleatorias: discretas y continuas.","Distribuciones: Binomial, Poisson, Normal, Exponencial, etc."]},
    {"titulo":"Probabilidad Avanzada","descripcion":"Modela fenómenos complejos y distribuciones de datos.","detalles":["Distribuciones multivariadas y condicionales.","Teorema central del límite.","Variables aleatorias discretas y continuas.","Esperanza matemática, varianza y covarianza."]},
    {"titulo":"Estadística Paramétrica","descripcion":"Inferencia asumiendo distribución conocida.","detalles":["Pruebas t, ANOVA, regresión lineal.","Correlación de Pearson.","Modelos basados en Normalidad."]},
    {"titulo":"Estadística No Paramétrica","descripcion":"Inferencia sin asumir distribución específica.","detalles":["Chi-cuadrado.","Correlación de Spearman.","Pruebas de Mann-Whitney, Kruskal-Wallis."]},
    {"titulo":"Estadística Bayesiana","descripcion":"Probabilidades actualizadas con evidencia nueva.","detalles":["Inferencia Bayesiana.","Modelos jerárquicos.","Posterior, prior, likelihood."]},
    {"titulo":"Analítica Predictiva","descripcion":"Predice valores futuros usando modelos.","detalles":["Regresión lineal y múltiple.","Regresión logística.","Árboles de decisión, Random Forest, Gradient Boosting, XGBoost, LightGBM.","Redes neuronales y deep learning.","Modelos de series temporales: ARIMA, SARIMA, Prophet, Holt-Winters."]},
    {"titulo":"Analítica Prescriptiva","descripcion":"Recomienda acciones óptimas basadas en predicciones y restricciones.","detalles":["Optimización lineal y no lineal.","Optimización estocástica y multiobjetivo.","Simulación de escenarios.","Técnicas de planificación y decisiones basadas en datos."]},
    {"titulo":"Estadística Multivariada","descripcion":"Analiza varias variables al mismo tiempo.","detalles":["Análisis de componentes principales (PCA).","Análisis factorial.","Análisis de conglomerados (clustering, k-means, DBSCAN).","Matrices de correlación/covarianza.","Reducción de dimensionalidad: t-SNE, UMAP."]},
    {"titulo":"Muestreo Estadístico","descripcion":"Selección de muestras representativas.","detalles":["Muestreo aleatorio simple, estratificado, sistemático.","Tamaño de muestra y error estándar.","Técnicas de bootstrap."]},
    {"titulo":"Regresiones y Modelos de Machine Learning","descripcion":"Predicen resultados o clasifican datos usando patrones históricos.","detalles":["Regresiones lineales y polinomiales.","Regresión logística para clasificación.","Modelos regularizados: Ridge, Lasso, Elastic Net.","Árboles de decisión, Random Forest, Gradient Boosting, XGBoost, LightGBM.","Redes neuronales y deep learning."]},
    {"titulo":"Series Temporales y Forecasting","descripcion":"Analiza datos secuenciales para predecir tendencias futuras.","detalles":["Modelos ARIMA y SARIMA.","Modelos de suavizamiento exponencial.","Prophet (Facebook) para forecasting.","Holt-Winters.","Detección de estacionalidad, tendencias y anomalías."]},
    {"titulo":"Evaluación de Modelos","descripcion":"Mide qué tan bien funcionan los modelos predictivos o de clasificación.","detalles":["Métricas de regresión: RMSE, MAE, R².","Métricas de clasificación: precisión, recall, F1-score, AUC-ROC.","Matrices de confusión.","Validación cruzada, k-fold, holdout.","Curvas de aprendizaje."]},
    {"titulo":"Análisis Exploratorio de Datos (EDA)","descripcion":"Permite entender y preparar los datos antes de modelar.","detalles":["Limpieza y transformación de datos.","Detección de valores nulos y outliers (IQR, z-score).","Visualización avanzada: histogramas, boxplots, scatter plots, heatmaps, visualización interactiva.","Resúmenes estadísticos, correlaciones y análisis multivariado."]},
    {"titulo":"Simulación y Monte Carlo","descripcion":"Usa generación de datos aleatorios para modelar incertidumbre.","detalles":["Simulación de escenarios y procesos estocásticos.","Monte Carlo para estimación de probabilidades y valores esperados.","Optimización bajo incertidumbre."]},
    {"titulo":"Optimización y Toma de Decisiones","descripcion":"Ayuda a encontrar la mejor solución posible dentro de restricciones.","detalles":["Programación lineal y no lineal.","Optimización estocástica y multiobjetivo.","Teoría de colas y simulaciones de procesos.","Optimización de recursos, costos o tiempo.","Análisis de decisiones basado en datos."]}
];