const Matriz = {
    "Preguntas":[
        {
            "Item":2,
            "Pregunta_I":" Cuestiono la información antes de aceptarla como verdadera",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "Pregunta":"¿Cuestionas y verificas la veracidad de la información sobre problemas sociales antes de aceptarla como una verdad que guíe tu opinión o conducta?",
            "R1":"Acepto la información de forma automática.",
            "R2":"Solo dudo si la fuente me parece sospechosa.",
            "R3":"Comparo datos de vez en cuando antes de decidir.",
            "R4":"Suelo verificar la información en distintas fuentes.",
            "R5":"Evalúo críticamente toda información antes de creerla.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"La pregunta mide el hábito de pensamiento crítico aplicado al entorno social, especialmente frente a información compartida por otros. Evaluar este comportamiento es relevante porque influye en la forma en que el individuo procesa rumores, noticias o creencias sociales antes de reproducirlas."
        },{
            "Item":4,
            "Pregunta_I":" Identifico errores en mi razonamiento",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "Pregunta":"¿Te resulta fácil detectar una falla o contradicción en tu propia forma de pensar cuando analizas un problema social complejo?",
            "R1":"No logro ver errores en mi lógica.",
            "R2":"Me cuesta mucho aceptar que mi razonamiento puede estar equivocado.",
            "R3":"A veces noto mis errores, pero solo después de que alguien me los señala.",
            "R4":"Suelo identificar mis propias contradicciones mientras estoy reflexionando.",
            "R5":"Detecto y corrijo mis fallos de razonamiento de manera natural y constante.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Esta formulación sitúa la reflexión interna dentro de un conflicto interpersonal, permitiendo medir la capacidad de autocontrol cognitivo antes de responder socialmente. Se evalúa qué tan fácil es para el individuo detenerse, analizar y responder con conciencia en interacción con otros."
        },{
            "Item":6,
            "Pregunta_I":" Cambio de opinión cuando la evidencia lo justifica",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "Pregunta":"¿Qué tan de acuerdo estás con la práctica de modificar tu postura sobre un problema social cuando se te presenta evidencia lógica que demuestra que tu opinión inicial era incorrecta?",
            "R1":"Mantengo mi posición inicial aunque me presenten pruebas en contra.",
            "R2":"Me cuesta mucho aceptar que estoy equivocado y cambiar mi discurso.",
            "R3":"Solo cambio de opinión si la evidencia es abrumadora o me afecta.",
            "R4":"Estoy dispuesto a ajustar mis ideas si me demuestran que hay datos más válidos.",
            "R5":"Priorizo la verdad y la lógica sobre el hecho de tener la razón.",
            "Tipo de Respuesta":"Acuerdo",
            "T1":"Totalmente en desacuerdo",
            "T2":"En desacuerdo",
            "T3":"Ni de acuerdo ni en desacuerdo",
            "T4":"De acuerdo",
            "T5":"Totalmente de acuerdo",
            "Explicación":"La pregunta evalúa el nivel de acuerdo con la capacidad de ajustar creencias cuando existen argumentos sólidos. Esto permite medir apertura cognitiva y disposición al cambio racional, habilidades esenciales para la toma de decisiones responsables dentro de dinámicas sociales."
        },{
            "Item":10,
            "Pregunta_I":" Me cuesta estructurar mis pensamientos",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "Pregunta":"¿Te resulta fácil sentir que tus pensamientos sobre un tema social están desordenados o te cuesta darles una estructura clara?",
            "R1":"Mis pensamientos siempre están ordenados y claros.",
            "R2":"Logro estructurar bien mis ideas.",
            "R3":"A veces me confundo con tanta información.",
            "R4":"Frecuentemente me cuesta organizar lo que pienso.",
            "R5":"Mis ideas suelen ser un caos y no logro ordenarlas.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"La pregunta evalúa la dificultad para estructurar pensamientos al comunicarse socialmente, enfocándose en la claridad mental aplicada a la interacción con otros. Al ser una pregunta invertida, permite detectar limitaciones cognitivas en expresión y coherencia verbal en contextos colectivos."
        },{
            "Item":12,
            "Pregunta_I":" Comprendo por qué me siento como me siento",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "Pregunta":"¿Te resulta fácil entender la razón exacta de tu malestar o incomodidad cuando te encuentras en un entorno social?",
            "R1":"Siento la incomodidad pero no logro entender por qué me ocurre.",
            "R2":"Me cuesta mucho descifrar qué detonó mi malestar en ese momento.",
            "R3":"A veces comprendo el origen de mi incomodidad tras pensarlo mucho.",
            "R4":"Suelo identificar rápido qué situación o comentario me hizo sentir mal.",
            "R5":"Reconozco de inmediato la causa exacta de mi emoción social.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Se enfoca en la comprensión emocional y su origen, clave para regulación social. Las respuestas miden el nivel de interpretación emocional y autoconocimiento, necesario para actuar con mayor equilibrio en la convivencia."
        },{
            "Item":13,
            "Pregunta_I":" Expreso mis emociones de forma adecuada",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "Pregunta":"¿Te resulta fácil expresar tus emociones de manera tranquila y clara ante los demás, incluso cuando te sientes molesto o incómodo?",
            "R1":"No logro expresarlas; o exploto o me guardo todo.",
            "R2":"Me cuesta mucho encontrar las palabras o el tono adecuado.",
            "R3":"A veces me expreso bien, pero pierdo el control si hay presión.",
            "R4":"Suelo comunicar lo que siento sin herir a los demás.",
            "R5":"Expreso mis sentimientos con total asertividad y calma siempre.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Se reformula para medir expresión emocional observable en sociedad. Las respuestas representan niveles de control y comunicación emocional, reflejando cómo el individuo maneja sus emociones en interacción con otros."
        },{
            "Item":15,
            "Pregunta_I":" Me desbordo fácilmente emocionalmente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "Pregunta":"¿Sientes que tus emociones te sobrepasan o te desbordan, impidiéndote reaccionar de forma equilibrada ante los demás?",
            "R1":"Mantengo siempre el equilibrio, sin importar la intensidad emocional.",
            "R2":"Logro modular mis emociones antes de que me superen.",
            "R3":"En situaciones de mucha presión, pierdo mi centro emocional.",
            "R4":"Suelo sentirme desbordado y me cuesta recuperar la calma.",
            "R5":"Mis emociones me dominan totalmente y pierdo el control con facilidad.",
            "Tipo de Respuesta":"Frecuencia emocional",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"La pregunta se mantiene como conducta emocional desbordada en contexto social. Es invertida porque representa dificultad de regulación emocional. Las respuestas reflejan niveles de control emocional frente a presión social."
        },{
            "Item":19,
            "Pregunta_I":" Comprendo emociones complejas en mí",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "Pregunta":"¿Te resulta fácil desenredar y comprender tus sentimientos cuando experimentas varias emociones complejas o contradictorias al mismo tiempo?",
            "R1":"Me siento confundido y no logro entender qué me pasa realmente.",
            "R2":"Me cuesta mucho distinguir una emoción de otra cuando se mezclan.",
            "R3":"Entiendo mis emociones mixtas solo después de mucho análisis.",
            "R4":"Suelo identificar con claridad los diferentes sentimientos que tengo.",
            "R5":"Descifro mis emociones complejas con total precisión y rapidez.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Se mantiene la esencia de comprender emociones complejas, llevándola a situaciones sociales. Las respuestas miden profundidad emocional y claridad interna, clave para responder adecuadamente en sociedad."
        },{
            "Item":24,
            "Pregunta_I":" Identifico cómo influyo en mi entorno",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil identificar de manera clara las consecuencias positivas o negativas que tu presencia y comportamiento generan en tu entorno social?",
            "R1":"No percibo ninguna relación entre lo que hago y lo que sucede a mi alrededor.",
            "R2":"Me cuesta notar si mi comportamiento realmente influye en el bienestar de otros.",
            "R3":"Solo reconozco mi influencia si el impacto es muy directo o evidente.",
            "R4":"Suelo distinguir con claridad cómo mis actitudes afectan el clima de mi entorno.",
            "R5":"Identifico con precisión el impacto que causo en la sociedad.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Mide percepción del rol social del individuo y su influencia en la convivencia."
        },{
            "Item":27,
            "Pregunta_I":" Ajusto mi comportamiento cuando es necesario",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil ajustar tu comportamiento cuando notas que tus acciones afectan negativamente a los demás o al entorno?",
            "R1":"Nunca cambio mi comportamiento, aunque afecte a otros.",
            "R2":"Casi nunca lo cambio, incluso si me lo dicen.",
            "R3":"A veces lo ajusto, pero no siempre.",
            "R4":"Con frecuencia corrijo mi comportamiento cuando noto que afecta a alguien.",
            "R5":"Siempre intento ajustar mi conducta si veo que está generando un impacto negativo.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa adaptación social observable y capacidad de corregir conductas que afectan el entorno."
        },{
            "Item":29,
            "Pregunta_I":" Aprendo de mis errores",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil convertir un error cometido en tu entorno social en un aprendizaje real que modifique tu comportamiento futuro?",
            "R1":"No suelo aprender de mis errores y los repito.",
            "R2":"A veces lo intento, pero no cambio realmente.",
            "R3":"Depende del error, en algunos casos aprendo y en otros no.",
            "R4":"Con frecuencia aprendo de mis errores y trato de mejorar.",
            "R5":"Siempre aprendo de mis errores y cambio mi comportamiento cuando es necesario.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa aprendizaje conductual visible y responsabilidad social frente a consecuencias."
        },{
            "Item":30,
            "Pregunta_I":" Me observo internamente con frecuencia",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "Pregunta":"¿Te detienes a analizar cómo te comportas y qué impacto causas en quienes te rodean?",
            "R1":"Nunca me observo ni pienso en cómo actúo frente a otros.",
            "R2":"Casi nunca me cuestiono mi comportamiento.",
            "R3":"A veces lo hago, pero no es constante.",
            "R4":"Con frecuencia me observo y reflexiono sobre cómo actúo.",
            "R5":"Siempre estoy atento a mi comportamiento y al impacto que genero en mi entorno.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Mide autoobservación y monitoreo interno del comportamiento social para regular acciones."
        },{
            "Item":32,
            "Pregunta_I":" Identifico mis valores personales",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil identificar y mantener tus valores personales al momento de decidir cómo actuar frente a los demás?",
            "R1":"No tengo claros mis valores y actúo según la situación.",
            "R2":"A veces pienso en mis valores, pero no los aplico siempre.",
            "R3":"Depende del contexto, a veces sigo mis valores y a veces no.",
            "R4":"Casi siempre actúo basado en mis valores personales.",
            "R5":"Siempre tengo claros mis valores y los mantengo incluso si otros piensan diferente.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Mide claridad interna de valores y coherencia personal como base para regular la conducta social."
        },{
            "Item":34,
            "Pregunta_I":" Me resulta difícil entenderme",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil sentirte confundido o incapaz de entender tus propias actitudes al relacionarte con los demás?",
            "R1":"Generalmente entiendo por qué actúo como actúo en distintas situaciones.",
            "R2":"A veces me cuesta, pero normalmente logro comprenderme.",
            "R3":"En ocasiones me entiendo y en otras no.",
            "R4":"Con frecuencia me cuesta entender mis reacciones o decisiones.",
            "R5":"Casi siempre me siento confundido sobre mis propias actitudes y emociones.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Mide dificultad de autocomprensión, lo cual limita la regulación de la conducta social y la toma de decisiones consciente."
        },{
            "Item":35,
            "Pregunta_I":" Sé cómo reacciono ante presión",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil reconocer de antemano cómo vas a reaccionar cuando te encuentras bajo presión frente a los demás?",
            "R1":"Casi nunca sé cómo reacciono hasta que ya pasó.",
            "R2":"A veces me sorprendo con mi reacción y no la entiendo.",
            "R3":"Depende de la situación, a veces lo identifico y a veces no.",
            "R4":"Con frecuencia reconozco cómo reacciono cuando estoy bajo presión.",
            "R5":"Siempre sé cómo reacciono ante presión y puedo controlarlo mejor.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa reconocimiento anticipado de respuestas personales bajo presión, clave para regular la conducta frente a otros."
        },{
            "Item":37,
            "Pregunta_I":" Actúo sin conocer mis verdaderas intenciones",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil actuar sin tener claras tus verdaderas intenciones al relacionarte con los demás?",
            "R1":"Generalmente actúo con claridad sobre lo que quiero lograr.",
            "R2":"Sé cuáles son mis intenciones al actuar.",
            "R3":"A veces actúo con claridad y otras no.",
            "R4":"Con frecuencia actúo sin comprender mis verdaderas intenciones.",
            "R5":"Casi siempre hago cosas sin saber realmente por qué, y luego me arrepiento o me confundo.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa desconexión entre intención interna y conducta social, lo cual dificulta el autocontrol y la coherencia."
        },{
            "Item":44,
            "Pregunta_I":" Me cuesta entender emociones ajenas",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil sentirte confundido o incapaz de comprender lo que otra persona está sintiendo?",
            "R1":"Generalmente comprendo las emociones de otras personas.",
            "R2":"A veces me cuesta, pero logro entenderlas con esfuerzo.",
            "R3":"Algunas emociones las entiendo y otras no.",
            "R4":"Con frecuencia no entiendo las emociones de los demás.",
            "R5":"Casi siempre me cuesta comprender emociones ajenas, incluso cuando intentan explicarlas.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Mide dificultad para interpretar emociones ajenas; al ser invertida identifica limitaciones empáticas que afectan convivencia."
        },{
            "Item":45,
            "Pregunta_I":" Respondo con sensibilidad ante el dolor ajeno",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "Pregunta":"¿Demuestras sensibilidad y ofreces apoyo cuando percibes que alguien en tu entorno está pasando por un momento de dolor o dificultad?",
            "R1":"Nunca me importa lo que otros estén viviendo.",
            "R2":"Casi nunca reacciono con sensibilidad ante el dolor ajeno.",
            "R3":"A veces muestro sensibilidad, pero depende de la persona.",
            "R4":"Con frecuencia reacciono con respeto y apoyo cuando alguien sufre.",
            "R5":"Siempre respondo con sensibilidad y trato de ayudar o acompañar de forma adecuada.",
            "Tipo de Respuesta":"Conducta",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Evalúa conducta empática observable ante sufrimiento ajeno, esencial para convivencia y solidaridad social."
        },{
            "Item":47,
            "Pregunta_I":" Evito involucrarme emocionalmente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "Pregunta":"¿Qué tan de acuerdo estás con la idea de mantener una distancia emocional y evitar involucrarte en los problemas de los demás para proteger tu propia tranquilidad?",
            "R1":"Me involucro con respeto cuando alguien necesita apoyo emocional.",
            "R2":"Prefiero distancia, pero puedo acompañar si es necesario.",
            "R3":"Algunas veces me involucro y otras evito hacerlo.",
            "R4":"Evito involucrarme emocionalmente con los demás.",
            "R5":"Me aparto emocionalmente y prefiero no involucrarme aunque la persona lo necesite.",
            "Tipo de Respuesta":"Actitud",
            "T1":"Totalmente en desacuerdo",
            "T2":"En desacuerdo",
            "T3":"Ni de acuerdo ni en desacuerdo",
            "T4":"De acuerdo",
            "T5":"Totalmente de acuerdo",
            "Explicación":"Evalúa tendencia a evitar conexión emocional; invertida porque distancia constante limita convivencia y apoyo comunitario."
        },{
            "Item":49,
            "Pregunta_I":" Soy compasivo ante errores ajenos",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "Pregunta":"¿Respondes con comprensión y respeto cuando alguien de tu entorno comete un error, en lugar de criticarlo o juzgarlo con dureza?",
            "R1":"Siempre critico o juzgo los errores ajenos.",
            "R2":"Suelo señalar errores con dureza.",
            "R3":"Depende de mi estado de ánimo.",
            "R4":"Comprendo los errores ajenos y respondo con respeto.",
            "R5":"Soy compasivo y entiendo que todos pueden equivocarse.",
            "Tipo de Respuesta":"Conducta",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Evalúa compasión como conducta social observable; impacta convivencia y reduce conflictos en comunidad."
        },{
            "Item":52,
            "Pregunta_I":" Percibo situaciones antes de que ocurran",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "Pregunta":"¿Te resulta fácil notar señales o sensaciones previas que te indican lo que está por suceder antes de que las cosas ocurran realmente?",
            "R1":"No noto señales previas.",
            "R2":"Casi nunca percibo algo antes de que ocurra.",
            "R3":"A veces lo percibo, pero no estoy seguro.",
            "R4":"Casi siempre noto señales antes de que suceda algo.",
            "R5":"Siempre lo noto con claridad y suele cumplirse.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa percepción anticipada en contexto social sin sonar místico."
        },{
            "Item":54,
            "Pregunta_I":" Ignoro mis corazonadas",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "Pregunta":"Cuando tienes una corazonada o sensación sobre una situación, ¿Eliges ignorarla y seguir adelante como si nada?",
            "R1":"Siempre ignoro lo que siento.",
            "R2":"Casi siempre lo ignoro aunque dude.",
            "R3":"A veces lo ignoro.",
            "R4":"Casi nunca lo ignoro.",
            "R5":"Nunca lo ignoro, siempre lo considero.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Identifica desconexión interna. Es invertida porque ignorar intuición refleja menor conciencia."
        },{
            "Item":56,
            "Pregunta_I":" Integro intuición y análisis racional",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "Pregunta":"¿Te resulta fácil equilibrar lo que te dicta tu lógica con lo que te dice tu intuición al momento de tomar una decisión importante?",
            "R1":"No lo equilibro.",
            "R2":"Casi nunca lo logro.",
            "R3":"A veces lo intento.",
            "R4":"Casi siempre logro equilibrarlo.",
            "R5":"Siempre analizo y también escucho mi intuición.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa integración intuición-lógica, clave para decisiones responsables."
        },{
            "Item":60,
            "Pregunta_I":" Me desconecto de mis sensaciones internas",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "Pregunta":"¿Eliges ignorar una sensación de incomodidad interna para continuar con tus actividades como si no sintieras nada?",
            "R1":"Siempre ignoro lo que siento.",
            "R2":"Lo ignoro aunque me afecte.",
            "R3":"A veces lo ignoro.",
            "R4":"Casi nunca lo ignoro.",
            "R5":"Nunca lo ignoro, siempre lo reconozco y lo analizo.",
            "Tipo de Respuesta":"Frecuencia emocional",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Evalúa desconexión de sensaciones internas. Es invertida porque ignorarlas reduce conciencia."
        },{
            "Item":61,
            "Pregunta_I":" Mantengo atención en tareas importantes",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "Pregunta":"¿Te resulta fácil mantener tu concentración en una tarea o responsabilidad importante sin distraerte hasta haberla terminado?",
            "R1":"Me cuesta mucho mantener la atención, me desconcentro rápido.",
            "R2":"Pierdo la concentración.",
            "R3":"A veces me concentro, pero me distraigo con facilidad.",
            "R4":"Casi siempre logro mantener mi atención.",
            "R5":"Siempre me mantengo concentrado hasta terminar lo que debo hacer.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Se adapta el enfoque a responsabilidades reales y cotidianas. Evalúa capacidad de atención como base interna del desempeño social."
        },{
            "Item":62,
            "Pregunta_I":" Me distraigo con facilidad",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "Pregunta":"¿Te ocurre que, mientras realizas una tarea importante, terminas distrayéndote con facilidad por estímulos externos o pensamientos ajenos?",
            "R1":"Siempre me distraigo, incluso con cosas mínimas.",
            "R2":"Me distraigo y pierdo el ritmo.",
            "R3":"A veces me distraigo, depende del ambiente.",
            "R4":"Casi nunca me distraigo.",
            "R5":"Nunca me distraigo, mantengo el foco con facilidad.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Es invertida porque distraerse refleja menor enfoque. Permite medir control atencional en situaciones comunes."
        },{
            "Item":65,
            "Pregunta_I":" Mantengo disciplina personal",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "Pregunta":"¿Te resulta fácil mantener la constancia en tus actividades diarias para cumplir con tus compromisos?",
            "R1":"No tengo disciplina, dejo todo para después.",
            "R2":"Me cuesta mucho ser disciplinado.",
            "R3":"Depende del día, a veces sí, a veces no.",
            "R4":"Casi siempre logro ser disciplinado.",
            "R5":"Siempre soy disciplinado y cumplo mis obligaciones.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa disciplina como manifestación externa del enfoque y responsabilidad, relevante en vida social y laboral."
        },{
            "Item":70,
            "Pregunta_I":" Abandono metas fácilmente",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "Pregunta":"¿Te ocurre que, al enfrentar obstáculos o dificultades, terminas abandonando las metas que te habías propuesto?",
            "R1":"Siempre abandono cuando algo se pone difícil.",
            "R2":"Abandono mis metas por frustración.",
            "R3":"A veces abandono, depende de la situación.",
            "R4":"Casi nunca abandono, suelo insistir.",
            "R5":"Siempre persevero hasta lograrlo.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Es invertida porque abandonar metas refleja bajo enfoque y baja perseverancia, visible en el comportamiento social."
        },{
            "Item":74,
            "Pregunta_I":" Reacciono exageradamente ante problemas",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "Pregunta":"¿Sientes que tus reacciones son desproporcionadas o exageradas ante los problemas que surgen con los demás?",
            "R1":"Siempre reacciono exageradamente y pierdo el control.",
            "R2":"Exagero mis reacciones.",
            "R3":"A veces exagero, depende del estrés.",
            "R4":"Casi nunca reacciono exageradamente.",
            "R5":"Mantengo control emocional en situaciones difíciles.",
            "Tipo de Respuesta":"Frecuencia emocional",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Es invertida porque exagerar reacciones genera conflictos sociales. Evalúa estabilidad emocional observable."
        },{
            "Item":75,
            "Pregunta_I":" Tolero frustraciones",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil manejar la frustración cuando algo no sale como esperas, sin que eso afecte tu trato hacia los demás?",
            "R1":"No tolero frustraciones, me desquito o me altero.",
            "R2":"Me cuesta mucho tolerarlas.",
            "R3":"A veces lo manejo, depende del momento.",
            "R4":"Casi siempre tolero la frustración con control.",
            "R5":"Siempre tolero frustraciones y mantengo buen trato con otros.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Nivel N2 porque regula emociones internas antes de expresarlas. Ayuda a prevenir conflictos sociales."
        },{
            "Item":76,
            "Pregunta_I":" Regulo mi enojo adecuadamente",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil gestionar tu enojo para expresarlo de manera respetuosa sin herir a los demás?",
            "R1":"Cuando me enojo, suelo explotar o decir cosas hirientes.",
            "R2":"Muchas veces pierdo el control del enojo.",
            "R3":"A veces lo controlo, a veces no.",
            "R4":"Casi siempre manejo mi enojo de forma adecuada.",
            "R5":"Siempre regulo mi enojo y lo expreso con respeto.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa regulación externa del enojo, muy importante para convivencia y cooperación."
        },{
            "Item":78,
            "Pregunta_I":" Actúo con calma bajo presión",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil mantener la calma y actuar razonadamente cuando te encuentras bajo mucha presión?",
            "R1":"Bajo presión pierdo el control y actúo impulsivamente.",
            "R2":"Me cuesta mucho mantener la calma.",
            "R3":"A veces logro controlarme.",
            "R4":"Casi siempre actúo con calma bajo presión.",
            "R5":"Siempre actúo con calma y pienso antes de decidir.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa conducta observable bajo presión: estabilidad emocional en escenarios sociales críticos."
        },{
            "Item":82,
            "Pregunta_I":" Mi vida tiene sentido para mí",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "Pregunta":"¿Qué tan de acuerdo estás con la idea de que tus actividades diarias tienen un significado o sentido profundo para ti?",
            "R1":"No siento que mi vida tenga sentido.",
            "R2":"Casi nunca siento sentido en lo que hago.",
            "R3":"A veces siento sentido, depende del momento.",
            "R4":"Casi siempre siento que mi vida tiene sentido.",
            "R5":"Siempre siento que mi vida tiene un propósito claro.",
            "Tipo de Respuesta":"Actitud",
            "T1":"Totalmente en desacuerdo",
            "T2":"En desacuerdo",
            "T3":"Ni de acuerdo ni en desacuerdo",
            "T4":"De acuerdo",
            "T5":"Totalmente de acuerdo",
            "Explicación":"Evalúa procesamiento interno de significado personal que regula motivación y conducta social."
        },{
            "Item":83,
            "Pregunta_I":" Actúo alineado con mis objetivos",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "Pregunta":"¿Tus acciones diarias son coherentes con las metas y objetivos que te has propuesto alcanzar?",
            "R1":"Mis acciones no tienen relación con mis objetivos.",
            "R2":"Muchas veces actúo sin pensar en mis metas.",
            "R3":"A veces actúo alineado, otras no.",
            "R4":"Casi siempre mis acciones reflejan mis objetivos.",
            "R5":"Siempre actúo de acuerdo con mis objetivos y aspiraciones.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Evalúa manifestación externa del propósito: coherencia entre objetivos y comportamiento observable."
        },{
            "Item":84,
            "Pregunta_I":" Me siento perdido respecto a mi futuro",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "Pregunta":"¿Experimentas la sensación de estar perdido o sin un rumbo definido respecto a tu futuro?",
            "R1":"Tengo claridad sobre mi futuro.",
            "R2":"Tengo cierta claridad.",
            "R3":"Depende de la situación.",
            "R4":"Siento que no sé qué hacer con mi futuro.",
            "R5":"Me siento perdido y sin rumbo.",
            "Tipo de Respuesta":"Frecuencia emocional",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Es invertida porque sentirse perdido reduce propósito y dirección personal, afectando decisiones sociales."
        },{
            "Item":90,
            "Pregunta_I":" Planifico mi crecimiento personal",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "Pregunta":"¿Dedicas tiempo a planear cómo mejorar y crecer personalmente para alcanzar tus metas?",
            "R1":"No planifico mi crecimiento ni pienso en mejorar.",
            "R2":"Casi nunca planifico, actúo sin rumbo.",
            "R3":"A veces planifico, pero no lo mantengo.",
            "R4":"Casi siempre planifico mi crecimiento.",
            "R5":"Siempre planifico mi crecimiento y lo cumplo con constancia.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Evalúa fundamento interno de propósito: planificación orienta desarrollo personal y contribución social."
        },{
            "Item":93,
            "Pregunta_I":" Busco significado en experiencias difíciles",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "Pregunta":"¿Te resulta fácil encontrar un aprendizaje o un sentido profundo a las experiencias difíciles que te toca vivir?",
            "R1":"No busco significado en momentos difíciles.",
            "R2":"Casi nunca encuentro aprendizaje.",
            "R3":"A veces lo intento, depende del caso.",
            "R4":"Casi siempre trato de encontrar significado.",
            "R5":"Siempre busco un aprendizaje o sentido en lo difícil.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa la capacidad interna de resignificar experiencias difíciles como base de crecimiento y adaptación social."
        },{
            "Item":94,
            "Pregunta_I":" Me siento desconectado de lo trascendente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "Pregunta":"¿Sientes que has dejado de buscar un propósito que te exija ir más allá de tus límites actuales?",
            "R1":"No me siento desconectado, siempre encuentro sentido.",
            "R2":"Casi nunca me siento desconectado.",
            "R3":"A veces me siento desconectado.",
            "R4":"Casi siempre me siento desconectado.",
            "R5":"Siempre me siento desconectado de lo trascendente.",
            "Tipo de Respuesta":"Frecuencia emocional",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Es invertida porque desconexión simbólica reduce sentido y estabilidad emocional interna."
        },{
            "Item":98,
            "Pregunta_I":" Vivo sin cuestionar el sentido de la existencia",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "Pregunta":"¿Te ocurre que vives tu día a día sin detenerte a cuestionar el sentido de tu vida o lo que haces en el mundo?",
            "R1":"Cuestiono y reflexiono sobre el sentido de mi vida.",
            "R2":"Reflexiono sobre mi vida.",
            "R3":"A veces me cuestiono, a veces no.",
            "R4":"Siempre vivo sin reflexionar.",
            "R5":"Siempre vivo sin cuestionarme nada.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Es invertida porque ausencia de reflexión reduce conciencia trascendente y sentido cultural."
        },{
            "Item":99,
            "Pregunta_I":" Siento unidad con mi entorno",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "Pregunta":"¿Qué tan de acuerdo estás con la idea de que existe un vínculo profundo o unidad entre tú y el entorno (personas, naturaleza o comunidad) que te rodea?",
            "R1":"No siento conexión con mi entorno.",
            "R2":"Casi nunca siento conexión.",
            "R3":"A veces siento conexión.",
            "R4":"Casi siempre siento conexión.",
            "R5":"Siempre siento unidad y conexión con mi entorno.",
            "Tipo de Respuesta":"Actitud",
            "T1":"Totalmente en desacuerdo",
            "T2":"En desacuerdo",
            "T3":"Ni de acuerdo ni en desacuerdo",
            "T4":"De acuerdo",
            "T5":"Totalmente de acuerdo",
            "Explicación":"Evalúa integración emocional-social: sentido de unidad promueve respeto y cooperación."
        },{
            "Item":103,
            "Pregunta_I":" Me adapto creativamente a problemas",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "Pregunta":"¿Logras adaptar tu forma de actuar buscando soluciones nuevas cuando te enfrentas a un cambio o dificultad inesperada?",
            "R1":"No me adapto, me quedo bloqueado.",
            "R2":"Me cuesta adaptarme y casi no busco alternativas.",
            "R3":"Depende de la situación.",
            "R4":"Casi siempre me adapto buscando soluciones creativas.",
            "R5":"Siempre encuentro formas creativas de adaptarme y avanzar.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Evalúa manifestación externa: la creatividad se observa en adaptación real ante problemas."
        },{
            "Item":105,
            "Pregunta_I":" Disfruto imaginar posibilidades nuevas",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "Pregunta":"¿Qué tan de acuerdo estás con que disfrutas dedicar tiempo a imaginar nuevas formas de mejorar las cosas a tu alrededor?",
            "R1":"No disfruto imaginar posibilidades nuevas.",
            "R2":"Casi nunca pienso en posibilidades nuevas.",
            "R3":"A veces me gusta imaginar ideas nuevas.",
            "R4":"Casi siempre disfruto imaginar nuevas posibilidades.",
            "R5":"Siempre disfruto imaginar nuevas posibilidades y escenarios.",
            "Tipo de Respuesta":"Actitud",
            "T1":"Totalmente en desacuerdo",
            "T2":"En desacuerdo",
            "T3":"Ni de acuerdo ni en desacuerdo",
            "T4":"De acuerdo",
            "T5":"Totalmente de acuerdo",
            "Explicación":"Evalúa procesamiento interno emocional y mental que impulsa creatividad como motivación cultural."
        },{
            "Item":107,
            "Pregunta_I":" Exploro perspectivas poco convencionales",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "Pregunta":"¿Te interesa escuchar y analizar ideas poco comunes, incluso si son muy diferentes a las tuyas?",
            "R1":"Sigo mis propias ideas.",
            "R2":"Casi nunca exploro ideas diferentes.",
            "R3":"Depende del tema.",
            "R4":"Exploro ideas nuevas.",
            "R5":"Busco perspectivas poco convencionales.",
            "Tipo de Respuesta":"Actitud",
            "T1":"Totalmente en desacuerdo",
            "T2":"En desacuerdo",
            "T3":"Ni de acuerdo ni en desacuerdo",
            "T4":"De acuerdo",
            "T5":"Totalmente de acuerdo",
            "Explicación":"Evalúa apertura creativa como base interna para innovación y pensamiento flexible en sociedad."
        },{
            "Item":108,
            "Pregunta_I":" Evito asumir riesgos creativos",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "Pregunta":"¿Dejas de proponer ideas nuevas por miedo a lo que los demás puedan pensar o a equivocarte?",
            "R1":"Siempre propongo ideas, aunque me juzguen.",
            "R2":"A menudo propongo ideas aunque tenga miedo.",
            "R3":"A veces me da miedo, a veces no.",
            "R4":"Me limito por miedo al juicio.",
            "R5":"Evito proponer ideas por que los demás no me van a entender.",
            "Tipo de Respuesta":"Frecuencia emocional",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Es invertida porque evitar riesgos creativos reduce participación e innovación social observable."
        },{
            "Item":111,
            "Pregunta_I":" Vivo el momento actual conscientemente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "Pregunta":"¿Te resulta fácil mantener toda tu atención puesta en lo que está ocurriendo mientras interactúas con otras personas?",
            "R1":"Mi mente suele estar en otra parte.",
            "R2":"Muchas veces me distraigo aunque esté presente físicamente.",
            "R3":"Depende de la situación, a veces estoy atento y otras no.",
            "R4":"Generalmente me mantengo atento en el momento.",
            "R5":"Siempre estoy consciente del presente cuando interactúo con otros.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Se adapta a interacción social y mide regulación intermedia de atención y conciencia del momento."
        },{
            "Item":112,
            "Pregunta_I":" Mi mente se dispersa constantemente",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "Pregunta":"¿Sientes que tu mente se dispersa en pensamientos propios mientras otras personas te están hablando o algo está ocurriendo?",
            "R1":"Me concentro plenamente en lo que ocurre.",
            "R2":"Suelo mantenerme atento.",
            "R3":"A veces me pasa, depende del tema o el ambiente.",
            "R4":"Me distraigo incluso en conversaciones importantes.",
            "R5":"Me desconcentro y me pierdo en mis pensamientos.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Pregunta invertida porque la dispersión mental reduce presencia social y atención en la interacción."
        },{
            "Item":116,
            "Pregunta_I":" Me anticipo constantemente al futuro",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "Pregunta":"¿Te ocurre que, al estar con otras personas, tu mente se adelanta a preocuparse por lo que pasará después?",
            "R1":"Estoy atento y anticipo lo que pueda pasar.",
            "R2":"Me preocupo por lo que viene.",
            "R3":"A veces me anticipo, aveces no.",
            "R4":"Nunca me preocupo por el futuro en esos momentos.",
            "R5":"Vivo el momento con tranquilidad.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Pregunta invertida: anticipación excesiva reduce la atención social y la conexión presente."
        },{
            "Item":117,
            "Pregunta_I":" Observo mis pensamientos sin juzgarlos",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "Pregunta":"¿Te resulta fácil simplemente notar tus pensamientos y dejarlos pasar sin juzgarlos ni dejarte arrastrar por ellos?",
            "R1":"No noto mis pensamientos, solo reacciono.",
            "R2":"Casi nunca logro observarlos antes de actuar.",
            "R3":"A veces lo logro, depende del momento.",
            "R4":"Generalmente puedo observar lo que pienso antes de reaccionar.",
            "R5":"Siempre observo mis pensamientos y actúo con calma.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Fundamento interno: capacidad de observación mental como base de regulación social."
        },{
            "Item":124,
            "Pregunta_I":" Justifico conductas incorrectas",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "Pregunta":"¿Es aceptable buscar justificaciones o excusas?",
            "R1":"No es aceptable bajo ninguna circunstancia.",
            "R2":"Es preferible evitar las excusas y limitarse a los hechos.",
            "R3":"Es aceptable o no dependiendo de la importancia de la falta.",
            "R4":"Es aceptable si ayuda a manejar las consecuencias de la situación.",
            "R5":"Es una reacción natural y aceptable en cualquier circunstancia.",
            "Tipo de Respuesta":"Actitud",
            "T1":"Totalmente en desacuerdo",
            "T2":"En desacuerdo",
            "T3":"Ni de acuerdo ni en desacuerdo",
            "T4":"De acuerdo",
            "T5":"Totalmente de acuerdo",
            "Explicación":"Invertida: la justificación evita responsabilidad ética y afecta la convivencia."
        },{
            "Item":125,
            "Pregunta_I":" Me responsabilizo de mis actos",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "Pregunta":"¿Te haces cargo de las consecuencias de tus actos cuando estos afectan negativamente a los demás?",
            "R1":"La responsabilidad es de quien tiene la culpa.",
            "R2":"Me cuesta aceptar que fue mi culpa.",
            "R3":"A veces lo reconozco, depende de la persona.",
            "R4":"Asumo mi responsabilidad y busco corregir.",
            "R5":"Asumo mis actos y busco reparar el daño.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Conducta observable social (N3): responsabilidad fortalece confianza y reduce conflictos."
        },{
            "Item":126,
            "Pregunta_I":" Evalúo consecuencias morales",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil prever el impacto moral que tendrán tus decisiones sobre los demás antes de actuar?",
            "R1":"No pienso en consecuencias morales.",
            "R2":"Actúo sin considerar el impacto ético.",
            "R3":"A veces lo pienso, depende de la situación.",
            "R4":"Evalúo las consecuencias antes de actuar.",
            "R5":"Evalúo las consecuencias morales de mis decisiones.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Fundamento interno (N1): pensamiento moral previo guía conductas sociales responsables."
        },{
            "Item":130,
            "Pregunta_I":" Actúo con integridad",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "Pregunta":"¿Actúas de forma correcta por convicción propia, sin importar si los demás te están observando?",
            "R1":"Priorizo mi beneficio personal si sé que no habrá consecuencias.",
            "R2":"Suelo cumplir solo si hay reglas claras.",
            "R3":"Depende; si el beneficio es grande, me cuesta ser coherente.",
            "R4":"Trato de ser íntegro, como corregir un error propio sin que me lo pidan",
            "R5":"Mantengo mis principios siempre, como respetar una fila aunque esté solo.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Conducta observable (N3): mide consistencia ética en acciones concretas dentro de la sociedad."
        },{
            "Item":132,
            "Pregunta_I":" Mis acciones reflejan mis creencias",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "Pregunta":"¿Logras que tu comportamiento con los demás sea un reflejo fiel de tus creencias personales?",
            "R1":"Casi nunca mis acciones reflejan mis creencias.",
            "R2":"Muchas veces actúo distinto a lo que creo por presión social.",
            "R3":"A veces lo hago, depende del contexto.",
            "R4":"Generalmente actúo conforme a mis creencias.",
            "R5":"Siempre mis acciones reflejan lo que pienso y creo, incluso si no es fácil.",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Conducta observable (N3): coherencia social entre creencias internas y comportamiento público."
        },{
            "Item":133,
            "Pregunta_I":" Siento coherencia interna",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "Pregunta":"¿Experimentas una sensación de armonía o acuerdo entre tus pensamientos, tus sentimientos y tus acciones?",
            "R1":"No siento armonía interna.",
            "R2":"Siento que estoy dividido entre lo que pienso y hago.",
            "R3":"Siento coherencia, pero no siempre.",
            "R4":"Siento coherencia interna.",
            "R5":"Siento claridad y coherencia entre lo que pienso, siento y hago.",
            "Tipo de Respuesta":"Percepción emocional",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Procesamiento intermedio (N2): regula estabilidad interna y se refleja en relaciones sociales más armoniosas."
        },{
            "Item":134,
            "Pregunta_I":" Vivo en conflicto interno frecuente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "Pregunta":"¿Sientes que tus deseos, pensamientos y acciones chocan entre sí, generándote una sensación de conflicto interno?",
            "R1":"Mantengo coherencia interna en mis pensamientos.",
            "R2":"Suelo tener claridad con mis pensamientos.",
            "R3":"A veces siento conflicto interno, depende de la situación.",
            "R4":"Me siento dividido y confundido.",
            "R5":"Siempre siento conflicto interno y me cuesta decidir.",
            "Tipo de Respuesta":"Percepción emocional",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Invertida: mide desequilibrio interno que afecta la estabilidad emocional y social."
        },{
            "Item":140,
            "Pregunta_I":" Reconozco desequilibrios internos",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "Pregunta":"¿Te resulta fácil identificar cuándo tus emociones o hábitos están fuera de equilibrio antes de que impacten a los demás?",
            "R1":"No reconozco mis desequilibrios.",
            "R2":"Lo noto tarde, cuando ya afecté a alguien.",
            "R3":"Lo reconozco dependiendo del problema.",
            "R4":"Reconozco mis desequilibrios y ajusto.",
            "R5":"Identifico mis desequilibrios y busco corregir antes de afectar a otros.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Fundamento interno (N1): autopercepción básica de desequilibrios que previene conflictos sociales."
        },{
            "Item":142,
            "Pregunta_I":" Identifico contradicciones en mí",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil darte cuenta de que estás actuando en contra de lo que realmente piensas o crees?",
            "R1":"No noto contradicciones en mí.",
            "R2":"Casi nunca me doy cuenta cuando soy incoherente.",
            "R3":"A veces lo noto, pero no siempre.",
            "R4":"Detecto mis contradicciones.",
            "R5":"Identifico con claridad mis contradicciones internas.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Mide el fundamento interno: capacidad de autoobservación para regular conducta social."
        },{
            "Item":144,
            "Pregunta_I":" Me comporto distinto según conveniencia",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "Pregunta":"¿Adaptas tu comportamiento según lo que más te conviene en el momento, aunque no sea coherente con lo que crees?",
            "R1":"Mantengo mis principios sin excepciones.",
            "R2":"Prefiero ser fiel a mis valores.",
            "R3":"Depende de qué tanto me convenga.",
            "R4":"Me adapto para obtener ventajas.",
            "R5":"Priorizo mi beneficio sobre mis principios",
            "Tipo de Respuesta":"Hábito",
            "T1":"Nunca",
            "T2":"Casi nunca",
            "T3":"A veces",
            "T4":"Casi siempre",
            "T5":"Siempre",
            "Explicación":"Es invertida porque actuar por conveniencia reduce coherencia e integridad social."
        },{
            "Item":146,
            "Pregunta_I":" Reconozco cuando traiciono mis valores",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "Pregunta":"¿Te resulta fácil tomar decisiones que sean totalmente coherentes con tus valores personales?",
            "R1":"No noto cuando traiciono mis valores.",
            "R2":"Casi nunca lo reconozco.",
            "R3":"A veces lo noto, pero lo justifico.",
            "R4":"Reconozco y lo acepto.",
            "R5":"Siempre reconozco cuando traiciono mis valores, aunque sea incómodo.",
            "Tipo de Respuesta":"Capacidad",
            "T1":"Muy difícil",
            "T2":"Dificil",
            "T3":"Neutro",
            "T4":"Facil",
            "T5":"Muy fácil",
            "Explicación":"Evalúa conciencia moral interna: reconocer incoherencia es clave para responsabilidad social."
        },{
            "Item":149,
            "Pregunta_I":" Busco alineación interna constante",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "Pregunta":"¿Es fundamental para ti que tus acciones diarias coincidan con lo que piensas y sientes?",
            "R1":"Prefiero ser flexible y actuar según lo que la situación requiera.",
            "R2":"No suelo dar prioridad a la coherencia interna al tomar decisiones.",
            "R3":"A veces busco esa alineación, pero depende de la circunstancia.",
            "R4":"Intento que mis actos reflejen mis convicciones.",
            "R5":"Es esencial actuar siempre en armonía con mis principios.",
            "Tipo de Respuesta":"Actitud",
            "T1":"Totalmente en desacuerdo",
            "T2":"En desacuerdo",
            "T3":"Ni de acuerdo ni en desacuerdo",
            "T4":"De acuerdo",
            "T5":"Totalmente de acuerdo",
            "Explicación":"Mide procesamiento intermedio: autorregulación interna constante, clave para estabilidad social."
        }
    ]
}