const Matriz = {
    "Preguntas":[
        {
            "Item":1,
            "Pregunta":" Analizo diferentes perspectivas antes de tomar una decisión",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":2,
            "Pregunta":" Cuestiono la información antes de aceptarla como verdadera",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":3,
            "Pregunta":" Reflexiono sobre mis propios pensamientos",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":4,
            "Pregunta":" Identifico errores en mi razonamiento",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":5,
            "Pregunta":" Busco coherencia lógica en lo que pienso",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":6,
            "Pregunta":" Cambio de opinión cuando la evidencia lo justifica",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":7,
            "Pregunta":" Me dejo llevar por ideas sin analizarlas",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":8,
            "Pregunta":" Evalúo consecuencias antes de actuar",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":9,
            "Pregunta":" Organizo mentalmente la información compleja",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":10,
            "Pregunta":" Me cuesta estructurar mis pensamientos",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Cognitiva",
            "CriterioC":"Comprensión de problemas sociales.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":11,
            "Pregunta":" Identifico con claridad lo que siento",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":12,
            "Pregunta":" Comprendo por qué me siento como me siento",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":13,
            "Pregunta":" Expreso mis emociones de forma adecuada",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":14,
            "Pregunta":" Reconozco cuando una emoción influye en mi juicio",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":15,
            "Pregunta":" Me desbordo fácilmente emocionalmente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":16,
            "Pregunta":" Mantengo estabilidad emocional ante presión",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":17,
            "Pregunta":" Puedo calmarme cuando estoy alterado",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":18,
            "Pregunta":" Evito reconocer emociones negativas",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":19,
            "Pregunta":" Comprendo emociones complejas en mí",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Emocional",
            "CriterioC":"Sensibilidad hacia los demás.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":20,
            "Pregunta":" Actúo impulsivamente por emoción",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":21,
            "Pregunta":" Soy consciente del impacto de mis acciones",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":22,
            "Pregunta":" Reflexiono sobre mis decisiones diarias",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":23,
            "Pregunta":" Actúo de manera automática sin pensar",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":24,
            "Pregunta":" Identifico cómo influyo en mi entorno",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":25,
            "Pregunta":" Me cuestiono sobre mi forma de vivir",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":26,
            "Pregunta":" Reconozco mis fortalezas y debilidades",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":27,
            "Pregunta":" Ajusto mi comportamiento cuando es necesario",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":28,
            "Pregunta":" Vivo sin analizar mis experiencias",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":29,
            "Pregunta":" Aprendo de mis errores",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":30,
            "Pregunta":" Me observo internamente con frecuencia",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Conciencia",
            "CriterioC":"Percepción y responsabilidad frente al entorno.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":31,
            "Pregunta":" Reconozco patrones repetitivos en mí",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":32,
            "Pregunta":" Identifico mis valores personales",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":33,
            "Pregunta":" Comprendo mis motivaciones internas",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":34,
            "Pregunta":" Me resulta difícil entenderme",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":35,
            "Pregunta":" Sé cómo reacciono ante presión",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":36,
            "Pregunta":" Identifico mis límites personales",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":37,
            "Pregunta":" Actúo sin conocer mis verdaderas intenciones",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":38,
            "Pregunta":" Evalúo mi comportamiento después de actuar",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":39,
            "Pregunta":" Reconozco cuando estoy equivocado",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":40,
            "Pregunta":" Tengo claridad sobre quién soy",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Autoconciencia",
            "CriterioC":"Permite regular la propia conducta en relación con otros.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":41,
            "Pregunta":" Comprendo cómo se sienten los demás",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        },
        {
            "Item":42,
            "Pregunta":" Puedo ponerme en el lugar del otro",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":43,
            "Pregunta":" Percibo cambios emocionales en otros",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        },
        {
            "Item":44,
            "Pregunta":" Me cuesta entender emociones ajenas",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        },
        {
            "Item":45,
            "Pregunta":" Respondo con sensibilidad ante el dolor ajeno",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":46,
            "Pregunta":" Escucho activamente a otros",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":47,
            "Pregunta":" Evito involucrarme emocionalmente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        },
        {
            "Item":48,
            "Pregunta":" Considero perspectivas diferentes a la mía",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":49,
            "Pregunta":" Soy compasivo ante errores ajenos",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":50,
            "Pregunta":" Me afecta emocionalmente el sufrimiento de otros",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Empatía",
            "CriterioC":"Base de la participación ciudadana y la convivencia.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        },
        {
            "Item":51,
            "Pregunta":" Confío en mi intuición al decidir",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":52,
            "Pregunta":" Percibo situaciones antes de que ocurran",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":53,
            "Pregunta":" Detecto incongruencias sin explicación lógica inmediata",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":54,
            "Pregunta":" Ignoro mis corazonadas",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":55,
            "Pregunta":" Mi intuición suele ser acertada",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":56,
            "Pregunta":" Integro intuición y análisis racional",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":57,
            "Pregunta":" Actúo sin escuchar señales internas",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":58,
            "Pregunta":" Reconozco señales sutiles en el entorno",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":59,
            "Pregunta":" Confío en mi percepción interna",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "PonderacionN":0.22,
            "PonderacionC":0.0375,
            "PonderaciónP":0.0039601168811196
        },
        {
            "Item":60,
            "Pregunta":" Me desconecto de mis sensaciones internas",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Intuición",
            "CriterioC":"Guía decisiones, pero menos directamente social.",
            "Impacto":"Bajo",
            "PonderacionN":0.22,
            "PonderacionC":0.0375,
            "PonderaciónP":0.0039601168811196
        },
        {
            "Item":61,
            "Pregunta":" Mantengo atención en tareas importantes",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":62,
            "Pregunta":" Me distraigo con facilidad",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":63,
            "Pregunta":" Prioritizo actividades relevantes",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":64,
            "Pregunta":" Completo lo que inicio",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":65,
            "Pregunta":" Mantengo disciplina personal",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":66,
            "Pregunta":" Me concentro incluso en entornos distractores",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":67,
            "Pregunta":" Postergó tareas importantes",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":68,
            "Pregunta":" Administro bien mi tiempo",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":69,
            "Pregunta":" Mantengo claridad en mis objetivos",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":70,
            "Pregunta":" Abandono metas fácilmente",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Enfoque",
            "CriterioC":"Más individual, aunque útil en proyectos colectivos.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":71,
            "Pregunta":" Controlo mis impulsos emocionales",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":72,
            "Pregunta":" Reformulo pensamientos negativos",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":73,
            "Pregunta":" Busco soluciones en lugar de reaccionar",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":74,
            "Pregunta":" Reacciono exageradamente ante problemas",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":75,
            "Pregunta":" Tolero frustraciones",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        },
        {
            "Item":76,
            "Pregunta":" Regulo mi enojo adecuadamente",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":77,
            "Pregunta":" Me cuesta manejar el estrés",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        },
        {
            "Item":78,
            "Pregunta":" Actúo con calma bajo presión",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":79,
            "Pregunta":" Reflexiono antes de responder emocionalmente",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":80,
            "Pregunta":" Evito enfrentar emociones difíciles",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Regulación Emocional",
            "CriterioC":"Evita conflictos y favorece la cooperación.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        },
        {
            "Item":81,
            "Pregunta":" Tengo metas claras en mi vida",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":82,
            "Pregunta":" Mi vida tiene sentido para mí",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":83,
            "Pregunta":" Actúo alineado con mis objetivos",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":84,
            "Pregunta":" Me siento perdido respecto a mi futuro",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":85,
            "Pregunta":" Trabajo por algo que considero significativo",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":86,
            "Pregunta":" Identifico mi vocación",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":87,
            "Pregunta":" Mis acciones reflejan mis aspiraciones",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":88,
            "Pregunta":" Me falta dirección personal",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":89,
            "Pregunta":" Mantengo motivación interna",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":90,
            "Pregunta":" Planifico mi crecimiento personal",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Propósito",
            "CriterioC":"Orienta acciones hacia metas colectivas.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":91,
            "Pregunta":" Siento conexión con algo más grande que yo",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "PonderacionN":0.22,
            "PonderacionC":0.0375,
            "PonderaciónP":0.0039601168811196
        },
        {
            "Item":92,
            "Pregunta":" Reflexiono sobre el sentido profundo de la vida",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":93,
            "Pregunta":" Busco significado en experiencias difíciles",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":94,
            "Pregunta":" Me siento desconectado de lo trascendente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "PonderacionN":0.22,
            "PonderacionC":0.0375,
            "PonderaciónP":0.0039601168811196
        },
        {
            "Item":95,
            "Pregunta":" Experimento paz interior",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "PonderacionN":0.22,
            "PonderacionC":0.0375,
            "PonderaciónP":0.0039601168811196
        },
        {
            "Item":96,
            "Pregunta":" Integro valores espirituales en mi vida",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":97,
            "Pregunta":" Encuentro propósito en el sufrimiento",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":98,
            "Pregunta":" Vivo sin cuestionar el sentido de la existencia",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":99,
            "Pregunta":" Siento unidad con mi entorno",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "PonderacionN":0.22,
            "PonderacionC":0.0375,
            "PonderaciónP":0.0039601168811196
        },
        {
            "Item":100,
            "Pregunta":" Practico momentos de introspección profunda",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Trascendencia Simbólica",
            "CriterioC":"Aporta sentido cultural, pero menos práctico en conducta ciudadana.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":101,
            "Pregunta":" Genero ideas originales con facilidad",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":102,
            "Pregunta":" Busco soluciones innovadoras",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":103,
            "Pregunta":" Me adapto creativamente a problemas",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":104,
            "Pregunta":" Me cuesta pensar fuera de lo común",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":105,
            "Pregunta":" Disfruto imaginar posibilidades nuevas",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "PonderacionN":0.22,
            "PonderacionC":0.0375,
            "PonderaciónP":0.0039601168811196
        },
        {
            "Item":106,
            "Pregunta":" Transformo errores en oportunidades",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":107,
            "Pregunta":" Exploro perspectivas poco convencionales",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":108,
            "Pregunta":" Evito asumir riesgos creativos",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":109,
            "Pregunta":" Conecto ideas diferentes entre sí",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00785615420105604
        },
        {
            "Item":110,
            "Pregunta":" Expreso mi creatividad activamente",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Creatividad",
            "CriterioC":"Impulsa innovación social, aunque no siempre regula conducta.",
            "Impacto":"Bajo",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.0375,
            "PonderaciónP":0.00529297175372943
        },
        {
            "Item":111,
            "Pregunta":" Vivo el momento actual conscientemente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":112,
            "Pregunta":" Mi mente se dispersa constantemente",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":113,
            "Pregunta":" Soy consciente de mis sensaciones corporales",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":114,
            "Pregunta":" Escucho con atención plena",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":115,
            "Pregunta":" Disfruto experiencias sin distraerme",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":116,
            "Pregunta":" Me anticipo constantemente al futuro",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":117,
            "Pregunta":" Observo mis pensamientos sin juzgarlos",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":118,
            "Pregunta":" Mantengo atención plena en conversaciones",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":119,
            "Pregunta":" Me desconecto fácilmente del presente",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":120,
            "Pregunta":" Practico la atención consciente",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Presencia",
            "CriterioC":"Capacidad de estar atento en la interacción social.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":121,
            "Pregunta":" Actúo conforme a mis valores",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":122,
            "Pregunta":" Reflexiono sobre lo correcto antes de decidir",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":123,
            "Pregunta":" Mantengo coherencia entre lo que digo y hago",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":124,
            "Pregunta":" Justifico conductas incorrectas",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":125,
            "Pregunta":" Me responsabilizo de mis actos",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":126,
            "Pregunta":" Evalúo consecuencias morales",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":127,
            "Pregunta":" Defiendo principios aunque sea difícil",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":128,
            "Pregunta":" Cambio valores según conveniencia",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":129,
            "Pregunta":" Busco justicia en mis decisiones",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        },
        {
            "Item":130,
            "Pregunta":" Actúo con integridad",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Ética Interna",
            "CriterioC":"Regula comportamientos y conductas sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":131,
            "Pregunta":" Mantengo equilibrio entre pensamiento y emoción",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":132,
            "Pregunta":" Mis acciones reflejan mis creencias",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":133,
            "Pregunta":" Siento coherencia interna",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":134,
            "Pregunta":" Vivo en conflicto interno frecuente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":135,
            "Pregunta":" Integro aprendizajes en mi vida diaria",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":136,
            "Pregunta":" Me adapto sin perder mi identidad",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":137,
            "Pregunta":" Me siento fragmentado internamente",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":true,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "PonderacionN":0.22,
            "PonderacionC":0.05,
            "PonderaciónP":0.0041523555646691
        },
        {
            "Item":138,
            "Pregunta":" Mantengo estabilidad en distintas áreas de mi vida",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":139,
            "Pregunta":" Actúo alineado con mi propósito",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.05,
            "PonderaciónP":0.00548521043727893
        },
        {
            "Item":140,
            "Pregunta":" Reconozco desequilibrios internos",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Integración Personal",
            "CriterioC":"Favorece la armonía en grupos.",
            "Impacto":"Medio",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.05,
            "PonderaciónP":0.00804839288460553
        },
        {
            "Item":141,
            "Pregunta":" Pienso,siento y actúo de manera congruente",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":142,
            "Pregunta":" Identifico contradicciones en mí",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":143,
            "Pregunta":" Ajusto mis acciones cuando no son coherentes",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":144,
            "Pregunta":" Me comporto distinto según conveniencia",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":true,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":145,
            "Pregunta":" Mantengo consistencia en mis decisiones",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":146,
            "Pregunta":" Reconozco cuando traiciono mis valores",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":147,
            "Pregunta":" Corrijo incoherencias personales",
            "Nivel":"N3",
            "CriterioN":"Manifestación externa observable en la sociedad.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.306666666666667,
            "PonderacionC":0.1,
            "PonderaciónP":0.00625416517147691
        },
        {
            "Item":148,
            "Pregunta":" Cambio postura sin fundamento claro",
            "Nivel":"N1",
            "CriterioN":"Fundamento interno que sostiene la conducta social.",
            "P_Invertida":true,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.473333333333333,
            "PonderacionC":0.1,
            "PonderaciónP":0.00881734761880351
        },
        {
            "Item":149,
            "Pregunta":" Busco alineación interna constante",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        },
        {
            "Item":150,
            "Pregunta":" Me percibo como una persona íntegra",
            "Nivel":"N2",
            "CriterioN":"Procesamiento intermedio que regula y modula.",
            "P_Invertida":false,
            "Conciencia":"Coherencia Interna",
            "CriterioC":"Asegura consistencia entre valores y acciones sociales.",
            "Impacto":"Alto",
            "PonderacionN":0.22,
            "PonderacionC":0.1,
            "PonderaciónP":0.00492131029886708
        }
]
}